version: "3.8"
services:
  votacao-db:
    container_name: votacao-db
    image: bitnami/postgresql:latest
    restart: always
    volumes:
      - votacao-db:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=root 
      - POSTGRES_PASSWORD=root 
      - POSTGRES_DB=votacao
  votacao-api:
    container_name: votacao-api
    build: ./api
    restart: "always"
    volumes:
      - .:/app
    links:
      - votacao-db
    depends_on:
      - votacao-db          
    ports:
      - "3000:3000"
  votacao-web:
    container_name: votacao-web
    build: ./web
    restart: "always"
    volumes:
      - .:/app
    depends_on:
      - votacao-api
    ports:
      - "80:80"
volumes:
  votacao-db: